"""
Django settings for sewing_site project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import environ

env = environ.Env()
# reading .env file
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG_SET') == 'TRUE'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'webbcraftinggallery.com',
    'www.webbcraftinggallery.com',
]


# Application definition

INSTALLED_APPS = [
    'main_site',
    'django_recaptcha',
    'csp',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sewing_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sewing_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = env('TIMEZONE')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_ROOT = BASE_DIR / "bucket"
MEDIA_URL = "/media/"


# RECAPTCHA Settings
RECAPTCHA_PUBLIC_KEY = env('RECAP_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = env('RECAP_PRIVATE_KEY')


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Session Cookies
SESSION_COOKIE_SECURE = env('HTTPS') == 'TRUE'    # Ensures session cookies are only sent over HTTPS
CSRF_COOKIE_SECURE = env('HTTPS') == 'TRUE'       # Ensures CSRF cookies are only sent over HTTPS
SESSION_COOKIE_HTTPONLY = env('HTTPS') == 'TRUE'  # Prevents JavaScript access to session cookies


# HSTS Settings.
SECURE_HSTS_SECONDS = 31536000                             # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = env('HTTPS') == 'TRUE'    # Apply HSTS to subdomains
SECURE_HSTS_PRELOAD = env('HTTPS') == 'TRUE'               # Allow preloading into browsers
SECURE_SSL_REDIRECT = env('HTTPS') == 'TRUE'               # Redirect HTTP to HTTPS


# CSP Configuration - New Format (django-csp 4.0+)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),  # Default to same-origin only
        'script-src': (
            "'self'",
            "https://www.google.com",    # ReCAPTCHA
            "https://www.gstatic.com",   # ReCAPTCHA
            "'unsafe-inline'",           # Required for ReCAPTCHA
        ),
        'style-src': (
            "'self'",
            "https://fonts.googleapis.com",  # Google Fonts CSS
            "'unsafe-inline'",           # Sometimes needed for ReCAPTCHA
        ),
        'font-src': (
            "'self'",
            "https://fonts.gstatic.com",  # Google Fonts
        ),
        'img-src': (
            "'self'",  # Local images
            "data:",   # Allow data URIs for images (Bootstrap icons)
            "https://www.google.com",    # ReCAPTCHA images
            "https://www.gstatic.com",   # ReCAPTCHA images
        ),
        'connect-src': (
            "'self'",  # Local API calls
            "https://www.google.com",    # ReCAPTCHA API calls
        ),
        'frame-src': (
            "https://www.youtube.com",  # For embedded YouTube videos
            "https://www.youtube-nocookie.com",  # Privacy-enhanced YouTube embeds
            "https://www.google.com",  # For ReCaptcha
            "https://recaptcha.google.com", # Also for ReCaptcha
        ),
    },
}